### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "test@example6.com",
  "password": "password123"
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### Get User
GET http://localhost:3000/api/auth/user
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6IjY5MzcxMWIwLTliZTctNGJmMy1hZDY0LWY3YjlhYjExM2UwMyIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3RzZWpxYXZtYnJlamFtbG1mcW5kLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI5MzZhY2M3MS1iOWNjLTQxZmUtOGFlNi0yZjI2NjgzNTUyOGEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY3OTEyOTc5LCJpYXQiOjE3Njc5MDkzNzksImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiOTM2YWNjNzEtYjljYy00MWZlLThhZTYtMmYyNjY4MzU1MjhhIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3Njc5MDkzNzl9XSwic2Vzc2lvbl9pZCI6IjNjOGI4ZDAyLTcxYWQtNDE2Mi1iMzdlLTc3MDhhOWE0YmVmMSIsImlzX2Fub255bW91cyI6ZmFsc2V9.dgGbNtrzDuosumggDY4lKzAoms_ybVxvDh8_0Je4ZHGqwcuED6ToN7vGYaqZGYFQA-jidfpLpdf7f5U3ru6czQ

### Logout
POST http://localhost:3000/api/auth/logout
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6IjY5MzcxMWIwLTliZTctNGJmMy1hZDY0LWY3YjlhYjExM2UwMyIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3RzZWpxYXZtYnJlamFtbG1mcW5kLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI5MzZhY2M3MS1iOWNjLTQxZmUtOGFlNi0yZjI2NjgzNTUyOGEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY3OTEyOTc5LCJpYXQiOjE3Njc5MDkzNzksImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiOTM2YWNjNzEtYjljYy00MWZlLThhZTYtMmYyNjY4MzU1MjhhIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3Njc5MDkzNzl9XSwic2Vzc2lvbl9pZCI6IjNjOGI4ZDAyLTcxYWQtNDE2Mi1iMzdlLTc3MDhhOWE0YmVmMSIsImlzX2Fub255bW91cyI6ZmFsc2V9.dgGbNtrzDuosumggDY4lKzAoms_ybVxvDh8_0Je4ZHGqwcuED6ToN7vGYaqZGYFQA-jidfpLpdf7f5U3ru6czQ